M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-06-26T14:02:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-26T14:02:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X4.0Y-11.0
X4.0Y-56.0
X55.0Y-11.0
X55.0Y-56.0
M30
