export { ANIM_FPS, SCREEN_H, SCREEN_W } from './constants'
export { applyProtocolPacket } from './protocolBridge'
export { renderFace } from './render'
export { faceSetFlags, faceStateUpdate, faceTriggerGesture } from './state'
export type { FaceState } from './types'
export { createFaceState } from './types'
